stages:
- analysis
- test


.cppcheck:
  image: ubuntu:bionic
  stage: analysis
  before_script:
    - apt update
    - apt install -y --no-install-recommends cppcheck=1.82-1 python3-pygments python-pygments
    - cppcheck --version
  script:
    - mkdir cppcheck
    #- cppcheck . -I include/ --verbose --enable=all --inconclusive --language=c++ --error-exitcode=1
    - cppcheck . -I include/ --enable=all --inconclusive --xml-version=2 --force --library=windows,posix,gnu . 2> cppcheck/result.xml
    - cppcheck-htmlreport --source-encoding="iso8859-1" --title="my project name" --source-dir . --report-dir=cppcheck --file=cppcheck/result.xml
  artifacts:
    paths:
      - cppcheck/
    expire_in: 1 week

.build-ubuntu-lts:
    image: conanio/conangcc8
    stage: test
    before_script:
      - sudo apt update
      - sudo apt install python3 python3-pip -y ${ADDITIONAL_PACKAGES}
      - pip3 install --user gcovr
      - export PATH=$HOME/.local/bin:$PATH
      - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan

    script:
      - mkdir -p build && cd build
      - if [ -f ../conanfile.txt ]; then conan profile new autodetect --detect --force ; fi
      - if [ -f ../conanfile.txt ]; then conan install -pr autodetect .. --build missing -s compiler.libcxx=libstdc++11 ; fi

      - cmake ..
      - cmake --build .
      - ctest
      - make coverage
    artifacts:
      paths:
        - build/coverage/
      expire_in: 1 week


#build-gcc5:
#    extends: .build-gcc
#    image: conanio/gcc5

#build-gcc6:
#    extends: .build-gcc
#    image: conanio/gcc6

build-bionic-gcc7:
    extends: .build-ubuntu-lts
    image: conanio/gcc7
    variables:
        CC: '/usr/bin/gcc-7'
        CXX: '/usr/bin/g++-7'

build-focal-gcc8:
    extends: .build-ubuntu-lts
    image: conanio/gcc8
    variables:
        CC: '/usr/bin/gcc-8'
        CXX: '/usr/bin/g++-8'

build-focal-gcc9:
    extends: .build-ubuntu-lts
    image: conanio/gcc8
    variables:
        CC: '/usr/bin/gcc-9'
        CXX: '/usr/bin/g++-9'
        ADDITIONAL_PACKAGES: 'gcc-9 g++-9'

build-focal-clang10:
    extends: .build-ubuntu-lts
    image: conanio/gcc10
    variables:
        ADDITIONAL_PACKAGES: 'clang-10'
        CC: '/usr/bin/clang-10'
        CXX: '/usr/bin/clang++-10'

