stages:
- analysis
- test

.build-ubuntu-lts:
    image: conanio/conangcc8
    stage: test
    before_script:
      - sudo apt update
      - sudo apt install python3 python3-pip -y ${ADDITIONAL_PACKAGES}
      - pip3 install --user gcovr
      - export PATH=$HOME/.local/bin:$PATH
      - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
      - env
    script:
      - mkdir -p build && cd build

      - if [ -f ../conanfile.txt ]; then conan profile new autodetect --detect --force ; fi
      - if [ -f ../conanfile.txt ]; then conan install -pr autodetect .. --build missing ${ADDITIONAL_CONAN_FLAGS} ; fi

      - cmake .. ${ADDITIONAL_CMAKE_FLAGS}
      - cmake --build .
      - ctest
      - make coverage
    artifacts:
      paths:
        - build/coverage/
      expire_in: 1 week


#build-gcc5:
#    extends: .build-gcc
#    image: conanio/gcc5

#build-gcc6:
#    extends: .build-gcc
#    image: conanio/gcc6

build-bionic-gcc7:
    extends: .build-ubuntu-lts
    image: conanio/gcc7
    variables:
        CC: '/usr/bin/gcc-7'
        CXX: '/usr/bin/g++-7'
        ADDITIONAL_CMAKE_FLAGS: ''
        ADDITIONAL_CONAN_FLAGS: '-s compiler.libcxx=libstdc++11'

build-focal-gcc8:
    extends: .build-ubuntu-lts
    image: conanio/gcc8
    variables:
        CC: '/usr/bin/gcc-8'
        CXX: '/usr/bin/g++-8'
        ADDITIONAL_CMAKE_FLAGS: ''
        ADDITIONAL_CONAN_FLAGS: '-s compiler.libcxx=libstdc++11'

build-focal-gcc9:
    extends: .build-ubuntu-lts
    image: conanio/gcc10
    variables:
        CC: '/usr/bin/gcc-9'
        CXX: '/usr/bin/g++-9'
        ADDITIONAL_PACKAGES: 'gcc-9 g++-9'
        ADDITIONAL_CMAKE_FLAGS: ''
        ADDITIONAL_CONAN_FLAGS: '-s compiler.libcxx=libstdc++11'

build-focal-clang10:
    extends: .build-ubuntu-lts
    image: conanio/gcc10
    variables:
        CC: '/usr/bin/clang-10'
        CXX: '/usr/bin/clang++-10'
        ADDITIONAL_PACKAGES: 'clang-10'
        ADDITIONAL_CMAKE_FLAGS: ''
        ADDITIONAL_CONAN_FLAGS: '-s compiler.libcxx=libstdc++11'

